### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-firefox-settings#1]
@Kirek are the icons working for you?
Here, I don't think so... It looks like this:

![ff](https://cloud.githubusercontent.com/assets/11800714/13723481/51aaac3e-e867-11e5-96f1-d977dbd95e5c.png)

**Comment by Kirek** [comment]
I will recheck them

**Comment by oberon2007** [comment]
The icon shows correctly on the base64-testpage. However not in FF nor Palemoon for me.
I have tried to link to the favicon now instead with
``iconData=https://forum.manjaro.org/favicon.ico``
That doesn't work either. Maybe this feature is just still not really implemented in the browsers?

**Comment by Kirek** [comment]
The string generated by https://www.base64-image.de/ doesn't work, also it needs the "icon=" in addition of the "iconData="
Got the right base64 png text from exporting the bookmarks and copying the text here.
https://github.com/manjaro/manjaro-firefox-settings/commit/44f020ec303776caa6fc1b2e96724acc6f6ca78d

**Comment by oberon2007** [comment]
Great! It's working now! Thanks.

**Comment by Kirek** [comment]
Another thing, this may not work with Palemoon, the support for icon/iconData was introduced with firefox 45

**Comment by oberon2007** [comment]
Yes, doesn't work in Palemoon. But at least the one for the forum updates by itself when you have visited the page once. The homepage and wiki are apparently not providing favicons - that would need to be fixed on the sites, anyway :wink:  ...
